language: java
jdk:
 - openjdk8

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

addons:
  sonarcloud:
    organization: "antkorwin-github"
    token: $SONAR_CLOUD_KEY

after_success:
 - bash <(curl -s https://codecov.io/bash)