language: java
jdk:
 - oraclejdk8

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

addons:
  sonarcloud:
    organization: "antkorwin-github"
    token:
      secure: "faca0ba57e2786f53d9caa7099033aa000953f0f"

after_success:
 - mvn cobertura:cobertura
 - bash <(curl -s https://codecov.io/bash)
